### ISSUE TITLE
Blueprints missing empty new lines in between properties

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/blueprints#9]
There's 2 problems here:
1. Blueprints have lost any new lines between blocks in this repository as part of the migration
2. When Blueprints are rendered on the website or in Kestra, they also have no new lines even if the source file does have them.

_What do I mean by new lines?_

This is how I would format a Kestra Flow. It has a new line between `namespace` and `inputs` and `tasks`. It also has new lines between tasks, and any other blocks like `triggers`, `errors` etc. 
```yaml
id: dynamic
namespace: company.team

inputs:
  - id: dataset_url
    type: STRING
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    script: |
      import pandas as pd

      df = pd.read_csv("{{ inputs.dataset_url }}")
      total_revenue = df['total'].sum()

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Finish"
```
Currently, this is being formatted like this:
```yaml
id: dynamic
namespace: company.team
inputs:
  - id: dataset_url
    type: STRING
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    script: |
      import pandas as pd

      df = pd.read_csv("{{ inputs.dataset_url }}")
      total_revenue = df['total'].sum()
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Finish"
```
This is much harder to read, especially for a blueprint.

Example that has the correct formatting but is rendered incorrectly:
Source: https://github.com/kestra-io/blueprints/blob/latest-stable/s3-trigger-python.yaml
Blueprint: https://kestra.io/blueprints/s3-trigger-python

Another problem: 
Tasks with blocks of code (use the `|` or `>` syntax) inside of them seem to have new lines between each line. Example: https://github.com/kestra-io/blueprints/blob/latest-stable/python-subflow-component.yaml

## Tasks:
- [ ] Fix Blueprints to have correct formatting (both adding and removing new lines) - Product Team
- [x] Render Blueprints correctly in Kestra and on the website - Dev Team
